Make and use a source-able setup script.

diff --git a/canvas_root_io/test/io-rules-regression/standalone/run_standalone b/canvas_root_io/test/io-rules-regression/standalone/run_standalone
--- a/canvas_root_io/test/io-rules-regression/standalone/run_standalone
+++ b/canvas_root_io/test/io-rules-regression/standalone/run_standalone
@@ -18,12 +18,6 @@ EOF
   exit ${1:-1}
 }
 
-function find_cetmodules_dir()
-{
-  local latest_version_dir="$(ls -1d "${1}/cetmodules/"*.version | sort -V -r | head -1)"
-  echo "${latest_version_dir%.version}"
-}
-
 while getopts :cj:h OPT; do
   case $OPT in
     c)
@@ -43,10 +37,7 @@ done
 shift $(( OPTIND - 1 ))
 OPTIND=1
 TOP_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)
-
-CETMODULES_DIR="$(find_cetmodules_dir "${TOP_DIR}")"
-export CMAKE_PREFIX_PATH="${CETMODULES_DIR}${CMAKE_PREFIX_PATH:+:${CMAKE_PREFIX_PATH}}"
-export PATH="${CETMODULES_DIR}/bin:${PATH}"
+. ${TOP_DIR}/setup.sh || { echo "Unable to source setup script." 1>&2; exit 1; }
 cd ${TOP_DIR}/build
 if (( ${clean:-0} )); then
   rm -rf *
